### ISSUE TITLE
Access to your sample sharing drive

### ISSUE THREAD

**Issue by adi-dhole** [dineshssdn-867/Anomaly-Detection-CVPR2018#1]
Can you please provide the access to your Sample Size drive ink in Dataset folder?

**Comment by dineshssdn-867** [comment]
Sure I will change it to anyone with the link

**Comment by dineshssdn-867** [comment]
It's updated check it once now. 
Link: https://drive.google.com/drive/folders/1VHLuIsZZebUcY1g93NjONdM-8OVJcZR1?usp=sharing
